stages:
  prepare:
    cmd: python src/prepare.py data/CEDAR data/prepared/dataset.pkl
    deps:
    - data/CEDAR/
    - src/prepare.py
    params:
    - prepare.mode
    - prepare.fixed_size
    outs:
    - data/prepared/dataset.pkl:
        cache: false
  featurize:
    cmd: python src/featurize.py data/prepared/dataset.pkl data/features/dataset.pkl
    deps:
    - data/prepared/dataset.pkl
    - src/featurize.py
    params:
    - featurization.method
    - featurization.patterns_hist
    - featurization.polinom_coefficients_hist
    outs:
    - data/features/dataset.pkl:
        cache: false
  split:
    cmd: python src/split.py data/features/dataset.pkl data/splitted/train.pt data/splitted/test.pt
    deps:
    - data/features/dataset.pkl
    - src/split.py
    params:
    - split.salt
    outs:
    - data/splitted/train.pt:
        cache: false
    - data/splitted/test.pt:
        cache: false
  eval:
    cmd: python src/eval.py data/splitted/train.pt data/splitted/test.pt
    deps:
    - data/splitted/train.pt
    - data/splitted/test.pt
    - src/eval.py
    params:
    - eval.use_cls
    - eval.knn
    outs:
    - eval:
        cache: false
metrics:
- eval/metrics.json
plots:
- eval/plots/metrics:
    x: step
