stages:
  prepare:
    cmd: python .\src\prepare.py .\data\CEDAR .\data\prepared\dataset.pkl
    deps:
    - .\data\CEDAR\
    - .\src\prepare.py
    params:
    - prepare.mode
    outs:
    - .\data\prepared\dataset.pkl
  featurize:
    cmd: python .\src\featurize.py .\data\prepared\dataset.pkl .\data\features\dataset.pkl
    deps:
      - .\data\prepared\dataset.pkl
      - .\src\featurize.py
    params:
      - featurization.method
    outs:
      - .\data\features\dataset.pkl
  split:
    cmd: python .\src\split.py .\data\features\dataset.pkl .\data\splitted\train.pt .\data\splitted\test.pt
    deps:
      - .\data\features\dataset.pkl
      - .\src\split.py
    params:
      - split.salt
    outs:
      - .\data\splitted\train.pt
      - .\data\splitted\test.pt
  train:
      cmd: python .\src\train.py .\data\splitted\train.pt .\data\model\model.pkl
      deps:
        - .\data\splitted\train.pt
        - .\src\train.py
      outs:
        - .\data\model\model.pkl
  eval:
    cmd: python .\src\eval.py .\data\splitted\test.pt .\data\model\model.pkl
    deps:
      - .\data\splitted\train.pt
      - .\data\model\model.pkl
      - .\src\train.py
    outs:
      - .\eval
