general:
  cedar_path: ./data/BHSig260

prepare:
  mode: default # default thinned as_is
  fixed_size: 300,400 # Final size for all signatures (h,w)

featurization:
  method: lbp # hog lbp patterns_hist polinom_coefficients_hist
  patterns_hist:
    w_size: 3
  polinom_coefficients_hist:
    w_size: 3
    bins: 5,5


split:
  train_samples_per_user: 3
  salt: 4463

eval:
  use_cls: knn # knn svm  perceptron random_forest
  knn:
    k: 3
    metric: BHATTACHARYYA # EUCLIDEAN CITYBLOCK MANHATTAN BHATTACHARYYA CORRELATION KV_DIVERGENCE
