general:
  cedar_path: ./data/CEDAR

prepare:
  mode: thinned # default thinned
  fixed_size: 300,400 # Final size for all signatures (h,w)

featurization:
  method: polinom_coefficients_hist # hog lbp patterns_hist polinom_coefficients_hist
  patterns_hist:
    w_size: 6
  polinom_coefficients_hist:
    w_size: 6
    bins: 5,5


split:
  train_samples_per_user: 18
  salt: 44

eval:
  use_cls: knn
  knn:
    k: 6
    metric: BHATTACHARYYA # EUCLIDEAN CITYBLOCK MANHATTAN BHATTACHARYYA CORRELATION KV_DIVERGENCE
