general:
  cedar_path: ./data/CEDAR

prepare:
  mode: thinned
  fixed_size: 600,800 # Final size for all signatures (h,w)

featurization:
  method: hog

split:
  train_samples_per_user: 18
  salt: 44

eval:
  use_cls: knn
  knn:
    k: 6
    metric: BHATTACHARYYA # EUCLIDEAN CITYBLOCK MANHATTAN BHATTACHARYYA CORRELATION KV_DIVERGENCE
