general:
  cedar_path: ./data/CEDAR

prepare:
  mode: thinned
  fixed_size: 400,600 # Final size for all signatures (h,w)

featurization:
  method: hog

split:
  salt: 44

eval:
  use_cls: knn
  knn:
    k: 3
    metric: BHATTACHARYYA # EUCLIDEAN CITYBLOCK MANHATTAN BHATTACHARYYA CORRELATION KV_DIVERGENCE