general:
  cedar_path: ./data/CEDAR

prepare:
  mode: default
  fixed_size: 400,600 # Final size for all signatures (h,w)

featurization:
  method: hog

split:
  train_samples_per_user: 6
  salt: 44

eval:
  use_cls: knn
  knn:
    k: 5
    metric: BHATTACHARYYA # EUCLIDEAN CITYBLOCK MANHATTAN BHATTACHARYYA CORRELATION KV_DIVERGENCE
